/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Plant Tracker API
 * API for interacting with the Plant Tracker application
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityOutDescription } from "./activityOutDescription";

export interface ActivityOut {
  description?: ActivityOutDescription;
  id?: string;
  name: string;
}
