/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Plant Tracker API
 * API for interacting with the Plant Tracker application
 * OpenAPI spec version: 1.0.0
 */
import type { PlantOut } from "./plantOut";
import type { BulkPlantCreateResponseErrors } from "./bulkPlantCreateResponseErrors";

export interface BulkPlantCreateResponse {
  created?: PlantOut[];
  errors?: BulkPlantCreateResponseErrors;
}
