/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Plant Tracker API
 * API for interacting with the Plant Tracker application
 * OpenAPI spec version: 1.0.0
 */
import type { EntryInNotes } from "./entryInNotes";
import type { EntryInPlantHealth } from "./entryInPlantHealth";

export interface EntryIn {
  activities: string[];
  notes?: EntryInNotes;
  plant_health?: EntryInPlantHealth;
  plant_id: string;
  Timestamp: string;
}
