/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Plant Tracker API
 * API for interacting with the Plant Tracker application
 * OpenAPI spec version: 1.0.0
 */
import type { EntryPostNotes } from "./entryPostNotes";
import type { EntryPostPlantHealth } from "./entryPostPlantHealth";
import type { EntryPostPlantId } from "./entryPostPlantId";

export interface EntryPost {
  activities: string[];
  notes?: EntryPostNotes;
  plant_health?: EntryPostPlantHealth;
  plant_id?: EntryPostPlantId;
  Timestamp?: string;
}
