/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Book Store API
 * Book Store API for renting books and notifying available/returned books in a store
 * OpenAPI spec version: 1.0.0
 */
import type { EntryOutNotes } from "./entryOutNotes";
import type { EntryOutPhoto } from "./entryOutPhoto";

export interface EntryOut {
  activities: string[];
  id?: string;
  notes?: EntryOutNotes;
  photo?: EntryOutPhoto;
  plant: string;
  plant_health: number;
  Timestamp: string;
  user: string;
}
