/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Book Store API
 * Book Store API for renting books and notifying available/returned books in a store
 * OpenAPI spec version: 1.0.0
 */
import type { PlantPostCommonName } from "./plantPostCommonName";
import type { PlantPostName } from "./plantPostName";
import type { PlantPostNotes } from "./plantPostNotes";
import type { PlantPostScientificName } from "./plantPostScientificName";

export interface PlantPost {
  area_id?: string;
  common_name?: PlantPostCommonName;
  death_date?: string;
  graveyard?: boolean;
  name?: PlantPostName;
  notes?: PlantPostNotes;
  purchase_date?: string;
  scientific_name?: PlantPostScientificName;
}
