/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Plant Tracker API
 * API for interacting with the Plant Tracker application
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterIn {
  email: string;
  first_name: string;
  last_name: string;
  password: string;
  password_verify: string;
}
