/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Book Store API
 * Book Store API for renting books and notifying available/returned books in a store
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterIn {
  email: string;
  first_name: string;
  last_name: string;
  password: string;
  password_verify: string;
}
