/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Plant Tracker API
 * API for interacting with the Plant Tracker application
 * OpenAPI spec version: 1.0.0
 */

export type TrackerApiViewSearchSearchEntryParams = {
  query?: string;
  graveyard_only?: boolean;
  alive_only?: boolean;
};
