/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Book Store API
 * Book Store API for renting books and notifying available/returned books in a store
 * OpenAPI spec version: 1.0.0
 */

export type TrackerApiViewPlantPostPlantBodyCommonName = string | null;
