/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Book Store API
 * Book Store API for renting books and notifying available/returned books in a store
 * OpenAPI spec version: 1.0.0
 */
import type { TrackerApiViewPlantPostPlantBodyCommonName } from "./trackerApiViewPlantPostPlantBodyCommonName";
import type { TrackerApiViewPlantPostPlantBodyName } from "./trackerApiViewPlantPostPlantBodyName";
import type { TrackerApiViewPlantPostPlantBodyNotes } from "./trackerApiViewPlantPostPlantBodyNotes";
import type { TrackerApiViewPlantPostPlantBodyScientificName } from "./trackerApiViewPlantPostPlantBodyScientificName";

export type TrackerApiViewPlantPostPlantBody = {
  area_id?: string;
  common_name?: TrackerApiViewPlantPostPlantBodyCommonName;
  death_date?: string;
  file?: Blob | File;
  graveyard?: boolean;
  name?: TrackerApiViewPlantPostPlantBodyName;
  notes?: TrackerApiViewPlantPostPlantBodyNotes;
  purchase_date?: string;
  scientific_name?: TrackerApiViewPlantPostPlantBodyScientificName;
};
