/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Plant Tracker API
 * API for interacting with the Plant Tracker application
 * OpenAPI spec version: 1.0.0
 */
import type { TrackerApiViewEntryCreateEntryBodyNotes } from "./trackerApiViewEntryCreateEntryBodyNotes";
import type { TrackerApiViewEntryCreateEntryBodyPlantHealth } from "./trackerApiViewEntryCreateEntryBodyPlantHealth";

export type TrackerApiViewEntryCreateEntryBody = {
  activities: string[];
  file?: Blob;
  notes?: TrackerApiViewEntryCreateEntryBodyNotes;
  plant_health?: TrackerApiViewEntryCreateEntryBodyPlantHealth;
  plant_id: string;
  Timestamp: string;
};
