/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Plant Tracker API
 * API for interacting with the Plant Tracker application
 * OpenAPI spec version: 1.0.0
 */

export interface UserSchema {
  /** @maxLength 254 */
  email: string;
  /** @maxLength 255 */
  first_name: string;
  /** @maxLength 255 */
  last_name: string;
}
